#pragma once


#define VERSION "V: 0.1"

#define BOD 9600

#define UI_BACKEND_U8G2 0

#define UI_BACKEND UI_BACKEND_U8G2

#define BTN_BACKEND_ONE_BUTTON_FULL 0
#define BTN_BACKEND_ONE_BUTTON_TINY 1
#define BTN_BACKEND_CUSTOM 2

// #define BTN_BACKEND BTN_BACKEND_ONE_BUTTON_FULL
#define BTN_BACKEND BTN_BACKEND_ONE_BUTTON_TINY
// #define BTN_BACKEND BTN_BACKEND_CUSTOM

#define OLED_CLASS U8G2_SSD1306_128X64_NONAME_1_HW_I2C
// #define OLED_CLASS U8G2_SH1106_128X64_NONAME_1_HW_I2C

#define START_MENU_DURATION 1000 * 2


#define DEBOUNCE_DURATION 50